src/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TerrUser__c.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>TerrUsers</relationshipLabel>
        <relationshipName>TerrUsers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TerrUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TerrUser</label>
    <nameField>
        <displayFormat>TU-{00000}</displayFormat>
        <label>TerrUser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TerrUsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TerrUserTriggerHelper.cls
public with sharing class TerrUserTriggerHelper {

    public static Set<String> generateGroupMembersIds(List<TerrUser__c> terrUsers){
        Set<Id> territoryIds = new Set<Id>();
        for(TerrUser__c tu : terrUsers){
            territoryIds.add(tu.Territory__c);
        }
        Map<Id, String> groupNameByTerritoryId = new Map<Id, String>();
        for(Territory__c territory : [SELECT Id, Unique_Name__c FROM Territory__c WHERE Id IN: territoryIds]){
            groupNameByTerritoryId.put(territory.Id, territory.Unique_Name__c);
        }
        Map<String, Group> groupByName = new Map<String, Group>();
        for(Group gr : [SELECT Id, DeveloperName FROM Group WHERE DeveloperName IN: groupNameByTerritoryId.values()]){
            groupByName.put(gr.DeveloperName, gr);
        }
        Set<String> compositeIds = new Set<String>();
        for(TerrUser__c tu : terrUsers){
            compositeIds.add(groupByName.get(groupNameByTerritoryId.get(tu.Territory__c)).Id+ '_'+ tu.User__c);
        }
        return compositeIds;
    }

}